spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning
    username: root
    password: root
  thymeleaf:
    #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    cache: false
  web:
    resources:
      static-locations: classpath:/

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
